import { Suspense } from "react";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Onest } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import ToastProvider from "@/providers/toast-provider";
import FallbackLoader from "@/components/fallback-loader";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";

const onest = Onest({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Assistance.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${onest.className}} antialiased`}>
          <ConvexClientProvider>
            <Suspense fallback={<FallbackLoader />}>
              <NuqsAdapter>{children}</NuqsAdapter>
            </Suspense>
            <ToastProvider />
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
